'use strict';
/**
 * Session Ledger v3 core.
 * Source of truth: append-only hash-chained events.jsonl.
 * Derived: ledger.json, ledger.md, SQLite search index, summaries, relations.
 */
const fs=require('fs'), path=require('path'), os=require('os'), crypto=require('crypto'), zlib=require('zlib');
const SEC=require('./security'); const INT=require('./intelligence'); const IDX=require('./sqlite-index');
const OPS=new Set(['create','edit','view','delete','rename','bash','other']);
const MAX_DETAIL_BYTES=Number(process.env.LEDGER_MAX_DETAIL_BYTES||1024*1024), LOCK_WAIT_MS=Number(process.env.LEDGER_LOCK_WAIT_MS||10000), LOCK_STALE_MS=Number(process.env.LEDGER_LOCK_STALE_MS||30000);
function ledgerHome(){return process.env.LEDGER_HOME||path.join(os.homedir(),'.session-ledger');} function ensureDir(p){fs.mkdirSync(p,{recursive:true});}
function sleepMs(ms){const sab=new SharedArrayBuffer(4);Atomics.wait(new Int32Array(sab),0,0,ms);} function validateSessionId(id){if(typeof id!=='string'||!id||id.length>200)throw new Error('Invalid session id'); if(id==='.'||id==='..'||id.includes('/')||id.includes('\\')||id.includes('\0'))throw new Error('Invalid session id: path separators/traversal are not allowed');return id;}
function sessionDir(id){return path.join(ledgerHome(),'sessions',validateSessionId(id));}
function pidAlive(pid){if(!Number.isInteger(pid)||pid<=0)return false;try{process.kill(pid,0);return true;}catch(e){return e.code==='EPERM';}}
function lockOwner(d){try{return JSON.parse(fs.readFileSync(path.join(d,'owner.json'),'utf8'));}catch(_){return null;}} function lockIsStale(d){try{const st=fs.statSync(d);if(Date.now()-st.mtimeMs<=LOCK_STALE_MS)return false;const o=lockOwner(d);return !o||!pidAlive(Number(o.pid));}catch(_){return true;}}
function withLock(lockPath,fn){ensureDir(path.dirname(lockPath));const d=lockPath+'.lock',deadline=Date.now()+LOCK_WAIT_MS;while(true){try{fs.mkdirSync(d);fs.writeFileSync(path.join(d,'owner.json'),JSON.stringify({pid:process.pid,createdAt:new Date().toISOString()}));break;}catch(e){if(e.code!=='EEXIST')throw e;if(lockIsStale(d)){try{fs.rmSync(d,{recursive:true,force:true});}catch(_){}continue;}if(Date.now()>=deadline)throw new Error(`Timed out waiting for ledger lock: ${d}`);sleepMs(20+Math.floor(Math.random()*30));}}try{return fn();}finally{try{fs.rmSync(d,{recursive:true,force:true});}catch(_){}}}
function readJsonStrict(p,{missing=undefined}={}){try{return JSON.parse(fs.readFileSync(p,'utf8'));}catch(e){if(e.code==='ENOENT'&&missing!==undefined)return missing;throw new Error(`Failed to read JSON ${p}: ${e.message}`);}}
function fsyncDir(d){try{const fd=fs.openSync(d,'r');try{fs.fsyncSync(fd);}finally{fs.closeSync(fd);}}catch(_){}} function atomicWriteFile(p,c){ensureDir(path.dirname(p));const tmp=`${p}.tmp-${process.pid}-${crypto.randomBytes(4).toString('hex')}`,fd=fs.openSync(tmp,'w',0o600);try{fs.writeFileSync(fd,c);fs.fsyncSync(fd);}finally{fs.closeSync(fd);}fs.renameSync(tmp,p);fsyncDir(path.dirname(p));} function writeJsonAtomic(p,o){atomicWriteFile(p,JSON.stringify(o,null,2)+'\n');}
function newSessionId(){return `${new Date().toISOString().replace(/[:.]/g,'-')}_${crypto.randomBytes(4).toString('hex')}`;} function normalizeText(v,max=10000){if(v==null)return null;const s=String(v);return s.length>max?`${s.slice(0,max)}…[truncated]`:s;} function normalizeLines(l){if(l==null)return null;const s=Number(l.start),e=l.end==null?s:Number(l.end);if(!Number.isInteger(s)||!Number.isInteger(e)||s<0||e<s)throw new Error('Invalid lines: expected non-negative integers with end >= start');return{start:s,end:e};}
function policyPath(){return path.join(ledgerHome(),'policy.json');} function loadPolicy(){const p=policyPath();try{return {...SEC.defaultPolicy(),...readJsonStrict(p)};}catch(e){if(/ENOENT/.test(e.message)){const d=SEC.defaultPolicy();writeJsonAtomic(p,d);return d;}throw e;}} function savePolicy(p){writeJsonAtomic(policyPath(),{...SEC.defaultPolicy(),...p});return loadPolicy();}
function normalizeEventInput(event){const op=event.op||'other';if(!OPS.has(op))throw new Error(`Invalid op: ${op}`);const pol=loadPolicy();let detailRaw=event.detail==null?null:String(event.detail),summary=normalizeText(event.summary||'',4000)||'',redactions=[];if(pol.redactSecrets){const a=SEC.redactSecrets(detailRaw),b=SEC.redactSecrets(summary);detailRaw=a.text;summary=b.text;redactions=[...new Set([...a.redactions,...b.redactions])];}if(pol.redactSensitivePathDetails&&SEC.isSensitivePath(event.path)&&detailRaw){detailRaw='[REDACTED_SENSITIVE_PATH_CONTENT]';redactions.push('SENSITIVE_PATH');}
 let detail=detailRaw,tr=false;if(detailRaw&&Buffer.byteLength(detailRaw,'utf8')>MAX_DETAIL_BYTES){detail=Buffer.from(detailRaw,'utf8').subarray(0,MAX_DETAIL_BYTES).toString('utf8')+'\n[detail truncated]';tr=true;}const base={op,tool:normalizeText(event.tool||'unknown',500),path:normalizeText(event.path,32768),fromPath:normalizeText(event.fromPath,32768),lines:normalizeLines(event.lines),summary,detail,detailTruncated:tr,beforeHash:normalizeText(event.beforeHash,256),afterHash:normalizeText(event.afterHash,256),parentEventSeq:event.parentEventSeq==null?null:Number(event.parentEventSeq),causedBy:event.causedBy||null,result:event.result||null}; const enrich=INT.enrichEvent(base),risk=SEC.eventRisk(base);return{...base,...enrich,risk,redactions:[...new Set(redactions)]};}
function hashEvent(e){return crypto.createHash('sha256').update(JSON.stringify(e)).digest('hex');} function appendLineDurable(p,line){ensureDir(path.dirname(p));const fd=fs.openSync(p,'a',0o600);try{const b=Buffer.from(line);let o=0;while(o<b.length)o+=fs.writeSync(fd,b,o,b.length-o);fs.fsyncSync(fd);}finally{fs.closeSync(fd);}}
function readEventsJsonl(p,{tolerateTrailingPartial=false}={}){let t;try{t=fs.readFileSync(p,'utf8');}catch(e){if(e.code==='ENOENT')return[];throw e;}if(!t)return[];const ls=t.split('\n'),ev=[];for(let i=0;i<ls.length;i++){if(!ls[i])continue;try{ev.push(JSON.parse(ls[i]));}catch(e){const last=i===ls.length-1||(i===ls.length-2&&ls.at(-1)==='');if(tolerateTrailingPartial&&last)break;throw new Error(`Corrupt event journal ${p} at line ${i+1}: ${e.message}`);}}return ev;}
function readSessionJournal(d){const p=path.join(d,'events.jsonl'),gz=path.join(d,'events.jsonl.gz');if(fs.existsSync(p))return readEventsJsonl(p);if(fs.existsSync(gz)){const t=zlib.gunzipSync(fs.readFileSync(gz)).toString('utf8');const tmp=path.join(d,`.read-${process.pid}-${crypto.randomBytes(3).toString('hex')}.jsonl`);try{fs.writeFileSync(tmp,t);return readEventsJsonl(tmp);}finally{try{fs.unlinkSync(tmp);}catch(_){}}}return null;}
function verifyChain(ev){let prev=null;for(let i=0;i<ev.length;i++){const e=ev[i];if(e.seq!==i+1)throw new Error(`Ledger sequence corruption at event ${i+1}`);if((e.prevHash||null)!==prev)throw new Error(`Ledger hash-chain break at event ${e.seq}`);const c={...e};delete c.hash;if(e.hash!==hashEvent(c))throw new Error(`Ledger hash mismatch at event ${e.seq}`);prev=e.hash;}return true;}
function escapeMdInline(v){return String(v??'').replace(/\\/g,'\\\\').replace(/([`*_{}\[\]()#+.!|>~-])/g,'\\$1').replace(/[\r\n]+/g,' ');} function fenced(d){let t='```';while(String(d).includes(t))t+='`';return `${t}text\n${d}\n${t}`;}
function buildSummary(meta,events){const counts={},files=new Set(),symbols=new Set(),tests=[],risks=[];for(const e of events){counts[e.op]=(counts[e.op]||0)+1;if(e.path)files.add(e.path);for(const s of e.symbols||[])symbols.add(`${s.type}:${s.name}`);if(e.testKind)tests.push({seq:e.seq,kind:e.testKind,command:e.summary,outcome:e.testOutcome||null,result:e.result||null});if((e.risk?.score||0)>=4)risks.push({seq:e.seq,score:e.risk.score,reason:e.risk.reason});}return{sessionId:meta.id,startedAt:meta.startedAt,endedAt:meta.endedAt||null,totalEvents:events.length,operations:counts,filesTouched:files.size,topFiles:[...files].slice(0,100),symbols:[...symbols].slice(0,100),tests:tests.slice(-50),highRiskEvents:risks.slice(-50),generatedAt:new Date().toISOString()};}
function renderMd(meta,events){const s=buildSummary(meta,events),out=[`# Session Ledger: ${escapeMdInline(meta.id)}`,'',`- Client: ${escapeMdInline(meta.client||'unknown')}`,`- Project: ${escapeMdInline(meta.project||'')}`,`- Cwd: ${escapeMdInline(meta.cwd||'')}`,`- Started: ${escapeMdInline(meta.startedAt||'')}`,`- Ended: ${escapeMdInline(meta.endedAt||'(in progress)')}`,`- Parent session: ${escapeMdInline(meta.parentSessionId||'')}`,'',`## Summary`,`- Events: ${s.totalEvents}` ,`- Files touched: ${s.filesTouched}`,`- High-risk events: ${s.highRiskEvents.length}`,'',`## Events (${events.length})`,''];for(const e of events){const li=e.lines?` L${e.lines.start}${e.lines.end!==e.lines.start?'-'+e.lines.end:''}`:'';const target=e.op==='rename'&&e.fromPath?`${e.fromPath} -> ${e.path||''}`:(e.path||'');out.push(`### #${e.seq} [${escapeMdInline(e.op)}] ${escapeMdInline(target)}${li}`,`- Time: ${escapeMdInline(e.ts)}`,`- Tool: ${escapeMdInline(e.tool)}`,`- Risk: ${e.risk?.score??0}/5${e.risk?.reason?` (${escapeMdInline(e.risk.reason)})`:''}`);if(e.language)out.push(`- Language: ${escapeMdInline(e.language)}`);if(e.changeType)out.push(`- Change type: ${escapeMdInline(e.changeType)}`);if(e.testKind)out.push(`- Test/build kind: ${escapeMdInline(e.testKind)}`);if(e.testOutcome)out.push(`- Test outcome: ${escapeMdInline(e.testOutcome)}`);if(e.symbols?.length)out.push(`- Symbols: ${escapeMdInline(e.symbols.map(x=>`${x.type}:${x.name}`).join(', '))}`);if(e.dependencies?.length)out.push(`- Dependencies: ${escapeMdInline(e.dependencies.join(', '))}`);if(e.summary)out.push(`- Summary: ${escapeMdInline(e.summary)}`);if(e.beforeHash)out.push(`- Before SHA256: ${escapeMdInline(e.beforeHash)}`);if(e.afterHash)out.push(`- After SHA256: ${escapeMdInline(e.afterHash)}`);if(e.parentEventSeq)out.push(`- Parent event: #${e.parentEventSeq}`);if(e.causedBy)out.push(`- Caused by: ${escapeMdInline(e.causedBy)}`);if(e.redactions?.length)out.push(`- Redactions: ${escapeMdInline(e.redactions.join(', '))}`);if(e.detail){out.push('- Detail:',fenced(e.detail));}out.push('');}return out.join('\n');}
function regenerateViewsUnlocked(id){const d=sessionDir(id),m=readJsonStrict(path.join(d,'meta.json')),ev=readSessionJournal(d)||[];verifyChain(ev);writeJsonAtomic(path.join(d,'ledger.json'),ev);atomicWriteFile(path.join(d,'ledger.md'),renderMd(m,ev));writeJsonAtomic(path.join(d,'summary.json'),buildSummary(m,ev));return ev;}
function rebuildIndexFromSessions(){const sessions={},root=path.join(ledgerHome(),'sessions');let ds=[];try{ds=fs.readdirSync(root,{withFileTypes:true});}catch(e){if(e.code!=='ENOENT')throw e;}for(const de of ds){if(!de.isDirectory())continue;try{validateSessionId(de.name);const m=readJsonStrict(path.join(root,de.name,'meta.json'));sessions[de.name]={startedAt:m.startedAt,endedAt:m.endedAt||null,client:m.client,project:m.project,cwd:m.cwd,parentSessionId:m.parentSessionId||null};}catch(_){}}return{sessions};}
function updateIndexEntry(m){const p=path.join(ledgerHome(),'index.json');withLock(p,()=>{let idx;try{idx=readJsonStrict(p,{missing:{sessions:{}}});}catch(e){try{fs.copyFileSync(p,`${p}.corrupt-${Date.now()}`);}catch(_){}idx=rebuildIndexFromSessions();}if(!idx.sessions||typeof idx.sessions!=='object')idx.sessions={};idx.sessions[m.id]={startedAt:m.startedAt,endedAt:m.endedAt||null,client:m.client,project:m.project,cwd:m.cwd,parentSessionId:m.parentSessionId||null};writeJsonAtomic(p,idx);});}
function createSessionWithId(id,{client,project,cwd,parentSessionId}={}){validateSessionId(id);if(parentSessionId)validateSessionId(parentSessionId);const d=sessionDir(id);ensureDir(d);const now=new Date().toISOString(),m={id,client:client||'unknown',project:project||path.basename(cwd||process.cwd()),cwd:cwd||process.cwd(),startedAt:now,endedAt:null,parentSessionId:parentSessionId||null};writeJsonAtomic(path.join(d,'meta.json'),m);if(!fs.existsSync(path.join(d,'events.jsonl')))atomicWriteFile(path.join(d,'events.jsonl'),'');regenerateViewsUnlocked(id);updateIndexEntry(m);return m;} function startSession(o={}){return createSessionWithId(newSessionId(),o);}
function ensureSession(id,o={}){validateSessionId(id);return withLock(path.join(sessionDir(id),'.init'),()=>{const mp=path.join(sessionDir(id),'meta.json');let m;try{m=readJsonStrict(mp);}catch(e){if(!/ENOENT/.test(e.message))throw e;return createSessionWithId(id,o);}let ch=false;for(const k of ['client','project','cwd','parentSessionId'])if((!m[k]||m[k]==='unknown')&&o[k]){m[k]=o[k];ch=true;}if(ch){writeJsonAtomic(mp,m);updateIndexEntry(m);}return m;});}
function migrateLegacyIfNeededUnlocked(id){const d=sessionDir(id),j=path.join(d,'events.jsonl');if(fs.existsSync(j)||fs.existsSync(path.join(d,'events.jsonl.gz')))return;const old=readJsonStrict(path.join(d,'ledger.json'),{missing:[]});if(!Array.isArray(old)||!old.length){atomicWriteFile(j,'');return;}let prev=null;const mig=old.map((x,i)=>{const n=normalizeEventInput(x||{}),base={seq:i+1,ts:x.ts||new Date().toISOString(),...n,prevHash:prev},full={...base,hash:hashEvent(base)};prev=full.hash;return full;});atomicWriteFile(j,mig.map(JSON.stringify).join('\n')+'\n');}
function endSession(id){validateSessionId(id);const d=sessionDir(id);return withLock(path.join(d,'session'),()=>{const mp=path.join(d,'meta.json'),m=readJsonStrict(mp);migrateLegacyIfNeededUnlocked(id);if(!m.endedAt)m.endedAt=new Date().toISOString();writeJsonAtomic(mp,m);regenerateViewsUnlocked(id);updateIndexEntry(m);return m;});}
function inferRelations(id,events,e){const rel=[];const recent=[...events].reverse().slice(0,50);if(e.parentEventSeq)rel.push({sessionId:id,fromSeq:e.parentEventSeq,toSeq:e.seq,type:'parent',detail:e.causedBy||''});if(e.path){const p=recent.find(x=>x.path===e.path);if(p)rel.push({sessionId:id,fromSeq:p.seq,toSeq:e.seq,type:'same-file',detail:e.path});}if(e.op==='bash'&&e.testKind){const p=recent.find(x=>['edit','create'].includes(x.op));if(p)rel.push({sessionId:id,fromSeq:p.seq,toSeq:e.seq,type:'change-to-test',detail:e.testKind});}return rel;}
function logEvent(id,event){validateSessionId(id);const d=sessionDir(id);return withLock(path.join(d,'session'),()=>{const m=readJsonStrict(path.join(d,'meta.json'));migrateLegacyIfNeededUnlocked(id);if(m.endedAt)throw new Error(`Session ${id} has ended; refusing to append event`);const p=path.join(d,'events.jsonl'),ev=readEventsJsonl(p);verifyChain(ev);const n=normalizeEventInput(event),base={seq:ev.length+1,ts:new Date().toISOString(),...n,prevHash:ev.length?ev.at(-1).hash:null},full={...base,hash:hashEvent(base)};appendLineDurable(p,JSON.stringify(full)+'\n');const next=ev.concat(full);writeJsonAtomic(path.join(d,'ledger.json'),next);atomicWriteFile(path.join(d,'ledger.md'),renderMd(m,next));writeJsonAtomic(path.join(d,'summary.json'),buildSummary(m,next));try{IDX.indexEvent(ledgerHome(),id,full);for(const r of inferRelations(id,ev,full))IDX.addRelation(ledgerHome(),r);}catch(_){}return full;});}
function listSessions(){const p=path.join(ledgerHome(),'index.json'),disk=rebuildIndexFromSessions();let cur={sessions:{}};try{const x=readJsonStrict(p,{missing:null});if(x?.sessions&&typeof x.sessions==='object')cur=x;}catch(e){try{fs.copyFileSync(p,`${p}.corrupt-${Date.now()}`);}catch(_){}}const merged={sessions:{...cur.sessions,...disk.sessions}};if(JSON.stringify(merged)!==JSON.stringify(cur))writeJsonAtomic(p,merged);return merged.sessions;}
function loadSessionEvents(id){const d=sessionDir(id),ev=readSessionJournal(d);if(ev){verifyChain(ev);return ev;}const legacy=readJsonStrict(path.join(d,'ledger.json'),{missing:[]});return Array.isArray(legacy)?legacy:[];} function loadSessionMeta(id){return readJsonStrict(path.join(sessionDir(id),'meta.json'),{missing:null});}
function currentSessionId({cwd,client}={}){let c=Object.entries(listSessions()).filter(([,s])=>!s.endedAt);if(cwd)c=c.filter(([,s])=>s.cwd===cwd);if(client)c=c.filter(([,s])=>s.client===client);c.sort((a,b)=>String(b[1].startedAt).localeCompare(String(a[1].startedAt)));return c[0]?.[0]||null;} function repairSession(id){return withLock(path.join(sessionDir(id),'session'),()=>regenerateViewsUnlocked(id));}
function createCheckpoint(id,{paths=[],reason='manual',seq=null}={}){validateSessionId(id);const m=loadSessionMeta(id);if(!m)throw new Error('Unknown session');const root=path.join(sessionDir(id),'checkpoints'),cp=`${String(seq||Date.now()).padStart(6,'0')}-${crypto.randomBytes(3).toString('hex')}`,dir=path.join(root,cp);ensureDir(dir);const manifest={id:cp,sessionId:id,createdAt:new Date().toISOString(),reason,seq,files:[]};for(const p0 of [...new Set(paths.filter(Boolean))]){const p=path.resolve(p0);let st;try{st=fs.statSync(p);}catch(_){manifest.files.push({path:p,exists:false});continue;}if(!st.isFile()||st.size>50*1024*1024){manifest.files.push({path:p,exists:true,skipped:true,reason:!st.isFile()?'not-file':'too-large'});continue;}const key=crypto.createHash('sha256').update(p).digest('hex'),dest=path.join(dir,key);fs.copyFileSync(p,dest);manifest.files.push({path:p,exists:true,size:st.size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),snapshot:key});}writeJsonAtomic(path.join(dir,'manifest.json'),manifest);return manifest;}
function listCheckpoints(id){const root=path.join(sessionDir(id),'checkpoints');let ds=[];try{ds=fs.readdirSync(root,{withFileTypes:true});}catch(e){if(e.code==='ENOENT')return[];throw e;}return ds.filter(x=>x.isDirectory()).map(x=>readJsonStrict(path.join(root,x.name,'manifest.json'))).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)));}
function restoreCheckpoint(id,cpId,{dryRun=false}={}){const dir=path.join(sessionDir(id),'checkpoints',path.basename(cpId)),m=readJsonStrict(path.join(dir,'manifest.json')),actions=[];for(const f of m.files){if(f.skipped)continue;if(!f.exists){actions.push({path:f.path,action:'delete-if-exists'});if(!dryRun)try{fs.rmSync(f.path,{force:true});}catch(_){}continue;}actions.push({path:f.path,action:'restore'});if(!dryRun){ensureDir(path.dirname(f.path));fs.copyFileSync(path.join(dir,f.snapshot),f.path);}}return{checkpoint:cpId,dryRun,actions};}
function autoCheckpoint(id,event,prePaths=[]){const pol=loadPolicy(),risk=SEC.eventRisk(event);if(risk.score<Number(pol.checkpointRiskAtOrAbove||4))return null;return createCheckpoint(id,{paths:prePaths.filter(Boolean),reason:`auto risk ${risk.score}: ${risk.reason}`});}
function replay(id,{commands=false,files=false}={}){return loadSessionEvents(id).filter(e=>!commands||e.op==='bash').filter(e=>!files||e.path).map(e=>({seq:e.seq,ts:e.ts,op:e.op,path:e.path,summary:e.summary,risk:e.risk?.score||0,symbols:e.symbols||[],testKind:e.testKind||null}));}
function searchIndexed(query,opts={}){try{return IDX.search(ledgerHome(),query,opts);}catch(_){return[];}} function rebuildSearchIndex(){return IDX.rebuild(ledgerHome(),listSessions(),loadSessionEvents);} function getSummary(id){const p=path.join(sessionDir(id),'summary.json');try{return readJsonStrict(p);}catch(_){const m=loadSessionMeta(id),e=loadSessionEvents(id);return buildSummary(m,e);}}
function ask(query,{session}={}){let rows=searchIndexed(query,{session,limit:20});if(!rows.length){const terms=String(query).toLowerCase().split(/\W+/).filter(x=>x.length>2);const ids=session?[session]:Object.keys(listSessions());for(const sid of ids)for(const e of loadSessionEvents(sid)){const h=`${e.path||''} ${e.summary||''} ${e.detail||''} ${(e.symbols||[]).map(x=>x.name).join(' ')}`.toLowerCase();if(terms.some(t=>h.includes(t)))rows.push({...e,session_id:sid});}rows=rows.slice(0,20);}return{query,matches:rows.map(r=>({session:r.session_id||session,seq:r.seq,ts:r.ts,op:r.op,path:r.path,summary:r.summary,language:r.language,changeType:r.change_type||r.changeType,risk:r.risk?.score??r.risk??0,testKind:r.test_kind||r.testKind||null}))};}

function buildDependencyGraph(id){const ev=loadSessionEvents(id),nodes=new Set(),edges=[],seen=new Set();for(const e of ev){if(!e.path)continue;nodes.add(e.path);for(const dep of e.dependencies||[]){const key=`${e.path}=>${dep}`;if(seen.has(key))continue;seen.add(key);edges.push({from:e.path,to:dep,seq:e.seq,language:e.language||null});}}return{sessionId:id,nodes:[...nodes],edges};}
function sessionTree(){const ss=listSessions(),children={};for(const [id,m] of Object.entries(ss)){const p=m.parentSessionId||null;(children[p]||(children[p]=[])).push(id);}for(const k of Object.keys(children))children[k].sort((a,b)=>String(ss[a]?.startedAt||'').localeCompare(String(ss[b]?.startedAt||'')));const build=id=>({id,...ss[id],children:(children[id]||[]).map(build)});return(children[null]||[]).map(build);}
function buildCorrelations(id){const ev=loadSessionEvents(id),out=[];for(let i=0;i<ev.length;i++){const fail=ev[i];if(!fail.testKind||!['FAIL','TIMEOUT'].includes(fail.testOutcome))continue;let changes=[];for(let j=i+1;j<ev.length;j++){const x=ev[j];if(['edit','create','delete','rename'].includes(x.op))changes.push(x);if(x.testKind===fail.testKind&&x.testOutcome==='PASS'){out.push({type:'failure-change-pass',testKind:fail.testKind,failedSeq:fail.seq,changeSeqs:changes.map(c=>c.seq),passedSeq:x.seq,files:[...new Set(changes.map(c=>c.path).filter(Boolean))],startedAt:fail.ts,resolvedAt:x.ts});break;}if(x.testKind===fail.testKind&&['FAIL','TIMEOUT'].includes(x.testOutcome))changes=[];}}
return out;}
function getRelations(id){try{return IDX.relations(ledgerHome(),id);}catch(_){return[];}}

function archiveSession(id){const m=loadSessionMeta(id);if(!m?.endedAt)throw new Error('Only ended sessions can be archived');const d=sessionDir(id),src=path.join(d,'events.jsonl'),dest=path.join(d,'events.jsonl.gz');if(fs.existsSync(dest))return dest;if(!fs.existsSync(src))throw new Error('No active journal to archive');const ev=readEventsJsonl(src);verifyChain(ev);atomicWriteFile(dest,zlib.gzipSync(fs.readFileSync(src),{level:9}));const check=zlib.gunzipSync(fs.readFileSync(dest)).toString('utf8');if(check!==fs.readFileSync(src,'utf8'))throw new Error('Archive verification failed');fs.unlinkSync(src);try{fs.unlinkSync(path.join(d,'ledger.json'));}catch(_){}return dest;}
function runRetention(){const pol=loadPolicy(),sessions=Object.entries(listSessions()).sort((a,b)=>String(b[1].startedAt).localeCompare(String(a[1].startedAt))),now=Date.now(),archived=[];const max=Math.max(0,Number(pol.retention?.maxSessions||500));for(let i=0;i<sessions.length;i++){const [id,s]=sessions[i],oldByAge=s.endedAt&&Number(pol.retention?.archiveEndedAfterDays)>=0&&(now-Date.parse(s.endedAt))>Number(pol.retention.archiveEndedAfterDays)*86400000,overLimit=i>=max;if(s.endedAt&&(oldByAge||overLimit)){try{archived.push(archiveSession(id));}catch(_){}}}return{sessions:sessions.length,archived};}
module.exports={OPS,ledgerHome,sessionDir,startSession,ensureSession,endSession,logEvent,listSessions,loadSessionEvents,loadSessionMeta,currentSessionId,renderMd,repairSession,validateSessionId,normalizeLines,verifyChain,loadPolicy,savePolicy,createCheckpoint,listCheckpoints,restoreCheckpoint,autoCheckpoint,replay,searchIndexed,rebuildSearchIndex,getSummary,ask,buildDependencyGraph,sessionTree,buildCorrelations,getRelations,archiveSession,runRetention,buildSummary};
