#!/usr/bin/env node
'use strict';
const http=require('http');const L=require('./lib/ledger');const port=Number(process.env.LEDGER_PORT||8766);
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function page(title,body){return `<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>body{font-family:system-ui;max-width:1300px;margin:28px auto;padding:0 16px;background:#111;color:#eee}a{color:#8ab4f8}.card{border:1px solid #444;border-radius:10px;padding:14px;margin:12px 0}table{border-collapse:collapse;width:100%;font-size:14px}td,th{border-bottom:1px solid #333;padding:7px;text-align:left;vertical-align:top}pre{white-space:pre-wrap;background:#1b1b1b;padding:12px;border-radius:8px}.risk4,.risk5{font-weight:700}.pill{display:inline-block;padding:2px 7px;border:1px solid #555;border-radius:99px;margin-right:4px}input{padding:8px;width:min(600px,80%)}button{padding:8px}</style>${body}`;}
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://x');res.setHeader('Content-Type','text/html; charset=utf-8');let body='';
if(u.pathname==='/search'){const q=u.searchParams.get('q')||'';let rows=[];try{rows=L.searchIndexed(q,{limit:100});}catch(_){}body=`<p><a href="/">← Sessions</a></p><h1>Search</h1><form><input name="q" value="${esc(q)}"><button>Search</button></form><table><tr><th>Session</th><th>#</th><th>Op</th><th>Path</th><th>Summary</th></tr>${rows.map(r=>`<tr><td><a href="/session/${encodeURIComponent(r.session_id)}">${esc(r.session_id)}</a></td><td>${r.seq}</td><td>${esc(r.op)}</td><td>${esc(r.path)}</td><td>${esc(r.summary)}</td></tr>`).join('')}</table>`;}
else if(u.pathname.startsWith('/session/')){const id=decodeURIComponent(u.pathname.slice(9));try{const m=L.loadSessionMeta(id),ev=L.loadSessionEvents(id),s=L.getSummary(id),corr=L.buildCorrelations(id),graph=L.buildDependencyGraph(id);body=`<p><a href="/">← Sessions</a></p><h1>${esc(id)}</h1><div class="card"><span class="pill">${esc(m.project)}</span><span class="pill">${esc(m.client)}</span><span class="pill">${ev.length} events</span><span class="pill">${s.filesTouched} files</span></div><h2>Summary</h2><pre>${esc(JSON.stringify(s,null,2))}</pre><h2>Resolved failure chains</h2><pre>${esc(JSON.stringify(corr,null,2))}</pre><h2>Dependency graph</h2><pre>${esc(JSON.stringify(graph,null,2))}</pre><h2>Timeline</h2><table><tr><th>#</th><th>Time</th><th>Op</th><th>Risk</th><th>Outcome</th><th>Path</th><th>Symbols</th><th>Summary</th></tr>${ev.map(e=>`<tr><td>${e.seq}</td><td>${esc(e.ts)}</td><td>${esc(e.op)}</td><td class="risk${e.risk?.score||0}">${e.risk?.score||0}</td><td>${esc(e.testOutcome||'')}</td><td>${esc(e.path)}</td><td>${esc((e.symbols||[]).map(x=>x.name).join(', '))}</td><td>${esc(e.summary)}</td></tr>`).join('')}</table>`;}catch(e){res.statusCode=404;body=`<h1>Error</h1><pre>${esc(e.message)}</pre>`;}}
else{const ss=Object.entries(L.listSessions()).sort((a,b)=>String(b[1].startedAt).localeCompare(String(a[1].startedAt)));body=`<h1>Session Ledger</h1><form action="/search"><input name="q" placeholder="Search files, symbols, summaries, details"><button>Search</button></form><table><tr><th>Session</th><th>Project</th><th>Client</th><th>Started</th><th>Ended</th><th>Parent</th></tr>${ss.map(([id,s])=>`<tr><td><a href="/session/${encodeURIComponent(id)}">${esc(id)}</a></td><td>${esc(s.project)}</td><td>${esc(s.client)}</td><td>${esc(s.startedAt)}</td><td>${esc(s.endedAt||'open')}</td><td>${esc(s.parentSessionId||'')}</td></tr>`).join('')}</table>`;}
res.end(page('Session Ledger',body));});server.listen(port,'127.0.0.1',()=>console.log(`Session Ledger dashboard: http://127.0.0.1:${port}`));
